// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYyT5QTl5pb7d2Q_XtwyuTT11ER7S0_Ng',
    appId: '1:117128382044:android:576055d24f08218747c899',
    messagingSenderId: '117128382044',
    projectId: 'mynotes-nycto',
    storageBucket: 'mynotes-nycto.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_VhT8628DbLXc5SLD6VCBeHnciSyYiuQ',
    appId: '1:117128382044:ios:5df72665bbe7493747c899',
    messagingSenderId: '117128382044',
    projectId: 'mynotes-nycto',
    storageBucket: 'mynotes-nycto.appspot.com',
    iosClientId: '117128382044-pdt74a4rotj6q0kegh0g1o16m24s1ii6.apps.googleusercontent.com',
    iosBundleId: 'com.nyctobits.mynotes',
  );
}
